In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import os
import numpy as np

In [3]:
path = '/workspace/open_source_work/TensorFlowTTS/dump_ljspeech/train/wavs/'
train_wav_dir = os.listdir(path)

In [18]:
calib = []
for i in range(5):
    np_name = train_wav_dir[i]
    np_file = np.load(path + np_name)
    calib.append(np_file)
calib_dataset = np.array(calib)
   

In [20]:
calib_dataset[1:10]

array([array([ 0.00350952,  0.00335693,  0.00482178, ..., -0.0005188 ,
       -0.0005188 , -0.0005188 ], dtype=float32),
       array([ 0.00268555,  0.00228882,  0.00143433, ..., -0.00079346,
       -0.00079346, -0.00079346], dtype=float32),
       array([-1.5258789e-04,  3.0517578e-05,  6.1035156e-05, ...,
        9.1552734e-05,  9.1552734e-05,  9.1552734e-05], dtype=float32),
       array([-3.0517578e-05, -9.1552734e-05, -6.1035156e-05, ...,
        3.0517578e-05,  3.0517578e-05,  3.0517578e-05], dtype=float32)],
      dtype=object)

## Vitis-AI 

In [22]:
tacotron2_model_path = './tacotron2_saved_model_english'
model = tf.keras.models.load_model(tacotron2_model_path)
 
model

In [23]:
from tensorflow_model_optimization.quantization.keras import vitis_quantize

quantizer = vitis_quantize.VitisQuantizer(model)

quantized_model = quantizer.quantize_model(calib_dataset = calib_dataset[1:100])

ValueError: Only tf.keras sequential or functional models can be transformed.

In [ ]:
# Save the model
quantized_model.save(save_dir + 'vitis-ai-quantized_mnist_model.h5')

In [ ]:
quantized_model.summary()

In [ ]:
!vai_c_tensorflow2 -h

In [ ]:
!vai_c_tensorflow2 -m mnist-results/vitis-ai-quantized_mnist_model.h5 -o mnist-results/ -n mnist_XIR